// 使用proto3语法

// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.3.0
// - protoc             v4.23.4
// source: hello.proto

package service

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.32.0 or later.
const _ = grpc.SupportPackageIsVersion7

const (
	SayHello_SayHello_FullMethodName = "/SayHello/SayHello"
)

// SayHelloClient is the client API for SayHello service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type SayHelloClient interface {
	SayHello(ctx context.Context, in *HelloRequest, opts ...grpc.CallOption) (*HelloResponse, error)
}

type sayHelloClient struct {
	cc grpc.ClientConnInterface
}

func NewSayHelloClient(cc grpc.ClientConnInterface) SayHelloClient {
	return &sayHelloClient{cc}
}

func (c *sayHelloClient) SayHello(ctx context.Context, in *HelloRequest, opts ...grpc.CallOption) (*HelloResponse, error) {
	out := new(HelloResponse)
	err := c.cc.Invoke(ctx, SayHello_SayHello_FullMethodName, in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// SayHelloServer is the server API for SayHello service.
// All implementations must embed UnimplementedSayHelloServer
// for forward compatibility
type SayHelloServer interface {
	SayHello(context.Context, *HelloRequest) (*HelloResponse, error)
	mustEmbedUnimplementedSayHelloServer()
}

// UnimplementedSayHelloServer must be embedded to have forward compatible implementations.
type UnimplementedSayHelloServer struct {
}

func (UnimplementedSayHelloServer) SayHello(context.Context, *HelloRequest) (*HelloResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method SayHello not implemented")
}
func (UnimplementedSayHelloServer) mustEmbedUnimplementedSayHelloServer() {}

// UnsafeSayHelloServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to SayHelloServer will
// result in compilation errors.
type UnsafeSayHelloServer interface {
	mustEmbedUnimplementedSayHelloServer()
}

func RegisterSayHelloServer(s grpc.ServiceRegistrar, srv SayHelloServer) {
	s.RegisterService(&SayHello_ServiceDesc, srv)
}

func _SayHello_SayHello_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(HelloRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(SayHelloServer).SayHello(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: SayHello_SayHello_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(SayHelloServer).SayHello(ctx, req.(*HelloRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// SayHello_ServiceDesc is the grpc.ServiceDesc for SayHello service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var SayHello_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "SayHello",
	HandlerType: (*SayHelloServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "SayHello",
			Handler:    _SayHello_SayHello_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "hello.proto",
}

const (
	Sing_Sing_FullMethodName = "/Sing/Sing"
)

// SingClient is the client API for Sing service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type SingClient interface {
	Sing(ctx context.Context, in *SingRequest, opts ...grpc.CallOption) (*SingResponse, error)
}

type singClient struct {
	cc grpc.ClientConnInterface
}

func NewSingClient(cc grpc.ClientConnInterface) SingClient {
	return &singClient{cc}
}

func (c *singClient) Sing(ctx context.Context, in *SingRequest, opts ...grpc.CallOption) (*SingResponse, error) {
	out := new(SingResponse)
	err := c.cc.Invoke(ctx, Sing_Sing_FullMethodName, in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// SingServer is the server API for Sing service.
// All implementations must embed UnimplementedSingServer
// for forward compatibility
type SingServer interface {
	Sing(context.Context, *SingRequest) (*SingResponse, error)
	mustEmbedUnimplementedSingServer()
}

// UnimplementedSingServer must be embedded to have forward compatible implementations.
type UnimplementedSingServer struct {
}

func (UnimplementedSingServer) Sing(context.Context, *SingRequest) (*SingResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method Sing not implemented")
}
func (UnimplementedSingServer) mustEmbedUnimplementedSingServer() {}

// UnsafeSingServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to SingServer will
// result in compilation errors.
type UnsafeSingServer interface {
	mustEmbedUnimplementedSingServer()
}

func RegisterSingServer(s grpc.ServiceRegistrar, srv SingServer) {
	s.RegisterService(&Sing_ServiceDesc, srv)
}

func _Sing_Sing_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(SingRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(SingServer).Sing(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Sing_Sing_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(SingServer).Sing(ctx, req.(*SingRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// Sing_ServiceDesc is the grpc.ServiceDesc for Sing service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var Sing_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "Sing",
	HandlerType: (*SingServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "Sing",
			Handler:    _Sing_Sing_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "hello.proto",
}
